defmodule App.Repo.TenantMigrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :customer_name, :text, null: false
    end

    create table(:order_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :product_name, :text, null: false
      add :size_name, :text
      add :quantity, :decimal, null: false
      add :price, :decimal, null: false

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_items_order_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:order_items, "order_items_order_id_fkey")

    drop table(:order_items, prefix: prefix())

    drop table(:orders, prefix: prefix())
  end
end
