defmodule App.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :domain, :text, null: false
    end

    create unique_index(:companies, ["domain"], name: "companies_unique_domain_index")
  end

  def down do
    drop_if_exists unique_index(:companies, ["domain"], name: "companies_unique_domain_index")

    drop table(:companies)
  end
end
