defmodule App.Repo.Migrations.OrderItemModifiers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:order_item_modifiers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :price, :decimal, null: false

      add :order_item_id,
          references(:order_items,
            column: :id,
            name: "order_item_modifiers_order_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:order_item_modifiers, "order_item_modifiers_order_item_id_fkey")

    drop table(:order_item_modifiers)
  end
end
